% stackwriter writes a stack to a multipage image
% function stackwriter(stack,outputpath,baseFilename,...
%                      prependToFilename,appendToFilename)
function stackwriter(stack,outputpath,baseFilename,...
                     prependToFilename,appendToFilename)
filename = [prependToFilename,baseFilename,appendToFilename,'.tif'];

% Write first stack-slice to new image file
imwrite(stack(:,:,1), fullfile(outputpath,[prependToFilename...
                                           baseFilename...
                                           appendToFilename...
                                           '.tif']))

% Append rest of stack-slices to image file
for k = 1:size(stack,3)
    imwrite(stack(:,:,k), fullfile(outputpath, filename),...
                                   'writemode', 'append');
end